name: CI

on:
  push:
    branches: [main]

env:
  WINDOWS_TBB_DOWNLOAD_LINK: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/64957c0f-37bf-4408-909c-37ff52fe5119/w_tbb_oneapi_p_2021.11.0.49526.exe
  WINDOWS_ICPX_DOWNLOAD_LINK: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/dc441d10-698c-417d-be6f-44a172f7ab77/w_dpcpp-cpp-compiler_p_2024.0.1.28_offline.exe
  WINDOWS_ONEAPI_PATH: C:\Program Files (x86)\Intel\oneAPI
 
jobs:
  windows:
    name: Test components installation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Intel® oneAPI Threading Building Blocks (oneTBB)
        shell: cmd
        run: |
          curl %WINDOWS_TBB_DOWNLOAD_LINK% --output tbb_install.exe
          tbb_install.exe -s -a --silent --eula accept -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0
          del tbb_install.exe
      - name: Install Intel® oneAPI DPC++/C++ Compiler
        shell: cmd
        run: |
          curl %WINDOWS_ICPX_DOWNLOAD_LINK% --output icpx_install.exe
          icpx_install.exe -s -a --silent --eula accept -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0
          del icpx_install.exe
      - name: Basic Test
        shell: cmd
        run: |
          "%WINDOWS_ONEAPI_PATH%\setvars.bat"
          sycl-ls
